import Head from "next/head";
import Image from "next/image";
import React from "react";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import cls from "classnames";
import Love from "./love";
import { API_BASE_URL, BEARER_BASE_TOKEN } from "../hooks/yelp-api/config";

export const getStaticProps = async () => {
  try {
    const res = await fetch(API_BASE_URL, {
      headers: {
        Authorization: `Bearer ${BEARER_BASE_TOKEN}`,
        Origin: "localhost",
        withCredentials: true,
      },
    });
    const data = await res.json();
    console.log(data);
    return { props: { yelp: data } };
  } catch (error) {
    console.log(error);
  }
};
export default function Home({ yelp }) {
  const handleOnBannerBtnClick = () => {
    console.log("clicked");
  };
  console.log(yelp);
  return (
    <React.Fragment>
      <div style={{ display: "flex", flexDirection: "column" }}>
        <div className={styles.container} style={{ margin: 0, padding: 0 }}>
          <Head>
            <title>Coffee Store</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <Banner
              buttonText={"Se butiker i närheten"}
              handleOnClick={handleOnBannerBtnClick}
            />
            <div className={styles.heroImage} style={{ margin: 50 }}>
              <Image src="/static/image.svg" width="500px" height="400px" />
            </div>
          </main>
        </div>
      </div>
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      ></div>
      <br />
      <div className={styles.cardLayout}>
        {yelp.businesses.map((item) => {
          return (
            <div key={item.id}>
              <Link href="/">
                <a className={styles.cardLink}>
                  <div className={cls("glass", styles.containers)}>
                    <div className={styles.cardHeaderWrapper}>
                      <h2 className={styles.cardHeader}>{item.name}</h2>
                    </div>
                    <div className={styles.cardImageWrapper}>
                      <img
                        src={item.image_url}
                        width={260}
                        height={160}
                        className={styles.cardImage}
                      />
                      <p
                        style={{
                          display: "flex",
                          justifyContent: "space-between",
                          color: "InfoText",
                        }}
                      >
                        <span>Telefon: {item.phone ? item.phone : "---"}</span>
                        <span>Betyg: {item.rating}</span>
                      </p>
                      <p style={{ width: 260,color: "blue" }}>
                        Address: {item.location.address1},&nbsp;
                        <span >
                          &nbsp;
                          {item.location.zip_code}
                        </span>{" "}
                        &nbsp;
                        {item.location.city}
                      </p>
                    </div>
                  </div>
                </a>
              </Link>
            </div>
          );
        })}
      </div>
      <br />
      <div className={styles.container} style={{ margin: 0, padding: 0 }}>
        <Love />
      </div>
    </React.Fragment>
  );
}
